language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - python manage.py sqlclear
  - python manage.py makemigrations
  - python magae.py migrate
script:
  - python manage.py test
